ci: add retries to install docker compose step in quality checks

diff --git a/.github/workflows/quality.yml b/.github/workflows/quality.yml
--- a/.github/workflows/quality.yml
+++ b/.github/workflows/quality.yml
@@ -66,10 +66,26 @@ jobs:
           python3 -m pip install -r requirements-dev.txt
 
       - name: Install Docker Compose
+        shell: bash
         run: |
-          curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          chmod +x /usr/local/bin/docker-compose
-          docker-compose --version
+          MAX_ATTEMPTS=3
+          for ATTEMPT_NUM in $(seq 1 $MAX_ATTEMPTS); do
+            echo "Attempt ${ATTEMPT_NUM}/${MAX_ATTEMPTS} to install Docker Compose..."
+            set -e
+            if \
+              curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/docker-compose/releases/latest | jq -r '.tag_name')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
+              chmod +x /usr/local/bin/docker-compose && \
+              docker-compose --version; then
+              echo "Docker Compose installed successfully!"
+              exit 0 
+            else
+              echo "Attempt ${ATTEMPT_NUM} failed. Retrying in 3 seconds..."
+              sleep 5
+            fi
+          done
+
+          echo "Failed to install Docker Compose after ${MAX_ATTEMPTS} attempts."
+          exit 1
 
       - name: Start Pebble server
         run: docker-compose -f simple_acme_dns/tests/docker-compose.yml up -d
